site_name: Kubernetes The Hard Way
pages:
  - Home: "index.md"
  - Prerequisites: 01-prerequisites.md
  - Installing the Client Tools: 02-client-tools.md
  - Provisioning Compute Resources: 03-compute-resources.md
  - Provisioning the CA and Generating TLS Certificates: 04-certificate-authority.md
  - Generating Kubernetes Configuration Files for Authentication: 05-kubernetes-configuration-files.md
  - Generating the Data Encryption Config and Key: 06-data-encryption-keys.md
  - Bootstrapping the etcd Cluster: 07-bootstrapping-etcd.md
  - Bootstrapping the Kubernetes Control Plane: 08-bootstrapping-kubernetes-controllers.md
  - Bootstrapping the Kubernetes Worker Nodes: 09-bootstrapping-kubernetes-workers.md
  - Configuring kubectl for Remote Access: 10-configuring-kubectl.md
  - Provisioning Pod Network Routes: 11-pod-network-routes.md
  - Deploying the DNS Cluster Add-on: 12-dns-addon.md
  - Smoke Test:  13-smoke-test.md
  - Cleaning Up: 14-cleanup.md
docs_dir: docs
theme: readthedocs
plugins:
    - search
